<?php

namespace AppBundle\Repository;

/**
 * NearbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NearbyRepository extends \Doctrine\ORM\EntityRepository
{
}
